---
- hosts: ec2_instances
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    # - name: Install Docker dependencies
    #   apt:
    #     name:
    #       - docker.io
    #       - python3-pip
    #     state: present

    - name: Add apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add docker repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        update_cache: true

    - name: Add user ubuntu to Docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Put docker-compose on server
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Trigger docker-compose.yml on remote system
      ansible.builtin.shell:
        cmd: sudo docker-compose up -d
        chdir: /home/ubuntu